
import streamlit as st
import pandas as pd
import io
from io import BytesIO

st.set_page_config(page_title="Failure Report Analyzer", layout="wide")

st.title("Failure Report Analyzer")
st.caption("Collate Input sheets → Append Analysis fields → Compute Tiers → Download Master Excel")

# ---- Embedded tier mapping (autogenerated from your Mapping sheet at build time) ----
MAPPING = {
  "tier1_errors": [
    "Article Type In Title",
    "Description Bullets",
    "Description Length",
    "Description Unicode",
    "Lv Title Length",
    "Ideal LVN",
    "LVN Presence Check",
    "LVN Sequence Check",
    "Ideal PDN",
    "PDN Presence Check",
    "PDN Sequence Check",
    "Specification Count",
    "Title Casing",
    "Title Length",
    "Title Unicode"
  ],
  "tier2_data_image_coherence": [
    "Attribute Image Match",
    "Black And White Flag",
    "Blacklisted Country Of Origin",
    "Brand Consistency Flag",
    "Celebrity Licensed Content Flag",
    "Color Inconsistency Flag",
    "Duplicate Images Flag",
    "Fake Photoshopped Flag",
    "Fit Consistency Flag",
    "Flat Shot Flag",
    "Gender Age Group Match Flag",
    "Geometric Distortion Flag",
    "Headless Flag",
    "Image Availability",
    "Image Completeness Flag",
    "Image Quality Issues Flag",
    "Inappropriate Content Flag",
    "Key Brand Logo Flag",
    "Poor Editing Artifacts Flag",
    "Product Consistency Flag",
    "Religious Political Content Flag",
    "Restricted Product Promotion Flag",
    "Text Infographic Logo Flag",
    "Watermark Flag"
  ],
  "tier2_size_fit_description_completeness": [
    "Material Care Info",
    "Standard Sizes In Chart"
  ],
  "tier2_article_type_consistency": [
    "Article Type Match Flag",
    "Country Of Origin Available",
    "Description Content Match (%)",
    "Importer Address Valid",
    "Importer Details Available",
    "Manufacturer Address Valid",
    "Manufacturer Details Available",
    "Net Quantity Available",
    "Net Quantity Unit Available",
    "Package Contains Info Available",
    "Packer Address Valid",
    "Packer Details Available",
    "Title Content Match (%)"
  ]
}

REQUIRED_ANALYSIS_COLS = ["Failure Rate", "Failure Summary", "Failure Report", "styleId"]

def normalize_pass_fail(val):
    if pd.isna(val):
        return "Failed"
    s = str(val).strip().lower()
    return "Pass" if s == "passed" else "Fail"

def compute_tier_flags(merged_df: pd.DataFrame) -> pd.DataFrame:
    out = merged_df.copy()
    for tier, cols in MAPPING.items():
        present = [c for c in cols if c in out.columns]
        if len(present) == 0:
            out[tier] = "N/A"
            continue
        mask_all_pass = out[present].applymap(normalize_pass_fail).eq("Pass").all(axis=1)
        out[tier] = mask_all_pass.map(lambda x: "Pass" if x else "Fail")
    return out

def collate_input_to_master(input_xls_bytes: bytes) -> pd.DataFrame:
    xls = pd.ExcelFile(io.BytesIO(input_xls_bytes))
    frames = []
    for sheet in xls.sheet_names:
        df = pd.read_excel(xls, sheet_name=sheet)
        if df.empty:
            continue
        df["Tab Name"] = sheet
        frames.append(df)
    if len(frames) == 0:
        return pd.DataFrame()
    master = pd.concat(frames, ignore_index=True)
    return master

def merge_analysis(master: pd.DataFrame, analysis_xls_bytes: bytes) -> pd.DataFrame:
    axls = pd.ExcelFile(io.BytesIO(analysis_xls_bytes))
    # Expecting 'Analysis Results' sheet
    a = pd.read_excel(axls, sheet_name="Analysis Results")
    # Ensure styleId exists
    if "styleId" not in a.columns:
        st.error("The 'Analysis Results' sheet must contain a 'styleId' column.")
        st.stop()
    # Join all columns, we only *need* the required ones, but also tier check columns
    cols_to_keep = list(dict.fromkeys(["styleId"] + REQUIRED_ANALYSIS_COLS + list(sum(MAPPING.values(), []))))
    a_keep = a[[c for c in cols_to_keep if c in a.columns]].copy()
    merged = master.merge(a_keep, on="styleId", how="left")
    return merged

# ---- UI ----
col1, col2 = st.columns(2)
with col1:
    input_file = st.file_uploader("Upload Input.xlsx (multiple tabs)", type=["xlsx"])
with col2:
    analysis_file = st.file_uploader("Upload Analysis.xlsx (must contain 'Analysis Results')", type=["xlsx"])

process = st.button("Generate Master File")

if process:
    if not input_file or not analysis_file:
        st.error("Please upload both Input.xlsx and Analysis.xlsx")
        st.stop()
    master = collate_input_to_master(input_file.read())
    if master.empty:
        st.warning("Input.xlsx has no rows.")
        st.stop()
    if "styleId" not in master.columns:
        st.error("Input.xlsx must contain a 'styleId' column in each sheet.")
        st.stop()
    merged = merge_analysis(master, analysis_file.read())
    # Append tiers
    final_df = compute_tier_flags(merged)
    # Show preview
    st.subheader("Preview (first 100 rows)")
    st.dataframe(final_df.head(100), use_container_width=True)
    # Download
    output = BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        final_df.to_excel(writer, sheet_name="Master", index=False)
    st.download_button(
        label="Download Master_Final.xlsx",
        data=output.getvalue(),
        file_name=f"Master_Final_20251106_0955.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

st.markdown("—")
st.caption("Tip: If a tier shows 'N/A', the required check columns were not found in the uploaded Analysis file.")
